Repository akveo/nebular, pull requests merged in 2018-02, with the labels that each got.

#189 Add theme variables for nb-checkbox
  docs/output.json
  e2e/checkbox.e2e-spec.ts
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/checkbox-test/checkbox-test.component.ts
  src/framework/theme/components/checkbox/_checkbox.component.theme.scss
  src/framework/theme/components/checkbox/checkbox.component.ts
  src/framework/theme/components/checkbox/checkbox.spec.ts
  src/framework/theme/styles/themes/_cosmic.scss
  src/framework/theme/styles/themes/_default.scss
Labels: action: review

#187 Feature/acl
  .angular-cli.json
  DEV_DOCS.md
  README.md
  docs/app/homepage/homepage.component.html
  docs/app/homepage/homepage.component.ts
  docs/articles/index.md
  docs/articles/security-acl-configuration.md
  docs/articles/security-install.md
  docs/articles/security-intro.md
  docs/google46533d2e7a851062.html
  docs/index.html
  docs/output.json
  docs/structure.ts
  docs/tsconfig.app.json
  docs/tsconfig.spec.json
  gulpfile.js
  karma.conf.js
  package-lock.json
  package.json
  src/app/acl-test/acl-test.component.ts
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/role.provider.ts
  src/backend/app.js
  src/framework/security/LICENSE.txt
  src/framework/security/README.md
  src/framework/security/directives/is-granted.directive.ts
  src/framework/security/index.ts
  src/framework/security/package.json
  src/framework/security/security.module.ts
  src/framework/security/security.options.ts
  src/framework/security/services/access-checker.service.ts
  src/framework/security/services/access-checker.spec.ts
  src/framework/security/services/acl.service.ts
  src/framework/security/services/acl.spec.ts
  src/framework/security/services/role.provider.ts
  tsconfig.publish.json
Labels: WIP

#203 Feature/popover
  docs/articles/concept-ui-kit.md
  docs/assets/images/components/popover.gif
  docs/structure.ts
  e2e/popover.e2e-spec.ts
  gulpfile.js
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/popover-test/popover-test.component.ts
  src/framework/theme/components/popover/_popover.component.theme.scss
  src/framework/theme/components/popover/helpers/adjustment.helper.ts
  src/framework/theme/components/popover/helpers/adjustment.spec.ts
  src/framework/theme/components/popover/helpers/model.ts
  src/framework/theme/components/popover/helpers/positioning.helper.ts
  src/framework/theme/components/popover/helpers/positioning.spec.ts
  src/framework/theme/components/popover/helpers/trigger.helper.ts
  src/framework/theme/components/popover/popover.component.scss
  src/framework/theme/components/popover/popover.component.ts
  src/framework/theme/components/popover/popover.directive.ts
  src/framework/theme/components/popover/popover.module.ts
  src/framework/theme/index.ts
  src/framework/theme/styles/global/_components.scss
  src/framework/theme/styles/themes/_cosmic.scss
  src/framework/theme/styles/themes/_default.scss
Labels: action: review, module:theme

#235 Feature/auth refatoring
  docs/app/docs/page/blocks/basic-blocks/ngd-methods-block.component.ts
  docs/articles/auth-install.md
  docs/articles/auth-intro.md
  docs/articles/auth-provider.md
  docs/articles/auth-token.md
  docs/articles/security-acl-configuration.md
  docs/output.json
  docs/structure.ts
  gulpfile.js
  karma.conf.js
  src/app/app.module.ts
  src/app/role.provider.ts
  src/framework/auth/auth.module.ts
  src/framework/auth/auth.options.ts
  src/framework/auth/components/login/login.component.ts
  src/framework/auth/components/logout/logout.component.ts
  src/framework/auth/components/register/register.component.ts
  src/framework/auth/components/request-password/request-password.component.ts
  src/framework/auth/components/reset-password/reset-password.component.ts
  src/framework/auth/services/auth-result.ts
  src/framework/auth/services/auth.service.ts
  src/framework/auth/services/auth.spec.ts
  src/framework/auth/services/index.ts
  src/framework/auth/services/interceptors/jwt-interceptor.ts
  src/framework/auth/services/interceptors/simple-interceptor.ts
  src/framework/auth/services/token.service.ts
  src/framework/auth/services/token/token-service.spec.ts
  src/framework/auth/services/token/token-storage.spec.ts
  src/framework/auth/services/token/token-storage.ts
  src/framework/auth/services/token/token.service.ts
  src/framework/auth/services/token/token.spec.ts
  src/framework/auth/services/token/token.ts
  src/framework/theme/components/checkbox/_checkbox.component.theme.scss
  src/framework/theme/services/theme.spec.ts
Labels: action: review

#226 feat(bootstrap): bootstrap update, ng-bootstrap, angular-cli
  DEV_DOCS.md
  package-lock.json
  package.json
  src/app/bootstrap-test/bootstrap-test.component.ts
  src/framework/theme/components/checkbox/_checkbox.component.theme.scss
  src/framework/theme/styles/global/bootstrap/_custom-forms.scss
  src/framework/theme/styles/global/bootstrap/_forms.scss
Labels: WIP
